version: '3.1'

services:
  spectral:
    build: .
    restart: always
    ports:
      - 3000:3000
      - 3001:3001

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db_data:/data/db
